# -*- coding: utf-8 -*-
"""522H0006_DangThanhNhan_Lab02_03.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ivvUqgrylz4Uyvk5IcIksSEFXHjtd15T

**Đặng Thành Nhân-MSSV:522H0006-Nhóm 8 tổ 2 -Lab2-3**
"""

# Exercise 1
import numpy as np

x = np.arange(1, 5+1)
b = np.arange(1, 6+1)
c = np.arange(1, 30+1)
d = np.arange(1, 25+1)
print("vx = ", x)
print("vb = ", b)
print("vc = ", c)
print("vd = ", d)
print()

#a
print("a) ")
A1 = np.tile(x, (5,1))
print("A1 =")
print(A1)
print()
A  = A1.T
print("A =")
print(A)
print()

#b
print("b) ")
B = np.tile(b, (6,1))
print("B = ")
print(B)
print()

#c
print("c) ")
C1 = np.reshape(c, (6, 5))
print("C1 =")
print(C1)
C = C1.T
print("C =")
print(C)
print()

#d
print("d) ")
D = np.reshape(d, (5, 5))
print("D =")
print(D)

# Exercise 2
import numpy as np
a = int(input())
b = int(input())
maxtrix_5x6 = np.random.randint(a, b, (5, 6))
print('Rand_5x6 = ')
print(maxtrix_5x6)

# Exercise 3
import numpy as np

x = np.arange(1, 9+1)
A = np.reshape(x, (3, 3))
print("A = ")
print(A)
print()
B = np.flip(A, 1)
print("B = ")
print(B)

# Exercise 4
import numpy as np

x = np.arange(1, 9+1)
A = np.reshape(x, (3, 3))
print("A = ")
print(A)
print()
B = np.flip(A, 0)
print("B = ")
print(B)

# Exercise 5

Y = np.array( [[1, 2, 16, 31, 22],
              [2, 8, 12, 21, 23],
              [4, 9, 11, 14, 25],
              [3, 6, 10, 16, 34]] )
print("Y = ")
print(Y)
print()

#a
print("a) ")
x = Y[1, 1:4]
print("x = ")
print(x)
print()

#b
print("b)" )
y = Y[:,2:3]
print("y = ")
print(y)
print()

#c
print("c) ")
A = Y[1:3, 1:4]
print("A = ")
print(A)
print()

#d
print("d) ")
B = Y[:, [0,2,4]]
print("B = ")
print(B)
print()

#e
print("e) ")
C = Y[1:4, [0,2,3,4]]
print("C = ")
print(C)
print()

#f
print("d)" )
D = np.where(Y>12, Y, 0)
print("D = ")
print(D)

# Exercise 6
import numpy as np
A = np.array([[2,4,1],
      [6,7,2],
      [3,5,9]])
print("A = ")
print(A)
print()

#a
print("a)" )
x1 = A[0, :]
print("x1 = ")
print(x1)
print()

#b
print("b)" )
Y = A[1:3, :]
print("Y = ")
print(Y)

# Exercise 7
import numpy as np
A = np.array([[2,7,9,7],
              [3,1,5,6],
              [8,1,2,5]])
print("A = ")
print(A)
print()

#a
print("a)")
B = A[:, [0, 2]]
print("B = ")
print(B)
print()

#b
print("b)")
C = A[1::2 , :]
print("C = ")
print(C)
print()

#c
print("c)")
print("A= ")
print(A.T)